### ISSUE TITLE
please provide a release tag

### ISSUE THREAD

**Issue by EricDeveaud** [adamhockenberry/bacphlip-py#2]
Hello, 

our policy is to install release tagged version on our cluster. 
please can you provide a release tag ?

checking the code I assume current version is 0.9.3 (based on init.py content) can you confirm ?

regards

Eric

**Comment by adamhockenberry** [comment]
Thanks for the note. Was waiting until publication to publish a version 1, so for now I've published a pre-release as v0.9.3-alpha. Should be able to find it under the releases tab. 

Adam

**Comment by EricDeveaud** [comment]
thanks
