### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by phiweger** [adamhockenberry/bacphlip-py#6]
Hi Adam,

Is the training data available somewhere? You mention Zenodo in the model train repo, but I cannot find a corresponding record there.

Thanks a lot for your help,
Best,

Adrian

**Comment by adamhockenberry** [comment]
Many thanks for pointing out that I never uploaded this! Was waiting on the review process to upload a final dataset, but alas it takes a long time, so I just went ahead and uploaded the current dataset. The link is here: https://doi.org/10.5281/zenodo.4058664 and I have also updated the README.md in the other repository with this link as well (https://github.com/adamhockenberry/bacphlip-model-dev). I note on Zenodo that the fullest explanation about how the dataset is structured is contained within the aforementioned model development repo/notebooks but it should still mostly make sense.

Let me know if you encounter any issues/questions and thanks for your feedback
